#!/usr/bin/env python
'''
    ./configure type1 type2 ...

Description

    Generate vector.h and vector.c for the input type list, e.g.

        ./configure float double int64

    Available types:
        typename   shortname
        float      f         for float  
        double     d         for double
        int8       b         for byte
        uint8      ub        for unsigned byte
        int16      s         for short
        uint16     us        for unsigned short
        int32      i         for integer
        uint32     u         for unsigned integer
        int64      l         for long
        uint64     ul        for unsigned long
        char       c         for char
        uchar      uc        for unsigned char
        size       sz        for size

    A test program is also generated for each type with the name test-{type}vector.c
    To build the test program, run

        ./build

    And to run use

        ./test-{type}vector

'''

import sys

import vectypes

def main():
    if len(sys.argv) < 2:
        sys.stdout.write(__doc__)
        sys.exit(45)

    types = sys.argv[1:]

    vectypes.generate_h(types)
    vectypes.generate_c(types)
    vectypes.generate_tests(types)

if __name__=="__main__":
    main()
