#!/usr/bin/env python

from fabricate import *
import sys, os
import optparse
from glob import glob

import vectypes

def get_test_cfiles():
    flist=glob('tests/test-*.c')
    return flist

parser = optparse.OptionParser()
# make an options list, also send to fabricate
optlist=[optparse.Option('--prefix','-p',default=sys.exec_prefix)]
parser.add_options(optlist)

options,args = parser.parse_args()
prefix=os.path.expanduser( options.prefix )

CC='gcc'


# need gnu99 for foreach
#CFLAGS=['-std=c99','-O2']
CFLAGS=['-std=gnu99','-O2']
LINKFLAGS=[]

sources = ['vector']


test_cfiles=get_test_cfiles()

prognames = [f.replace('.c','') for f in test_cfiles]

programs=[]
for progname in prognames:
    programs += [{'name':progname,'sources':sources+[progname]}]


def build():
    compile()
    link()

def compile():
    for prog in programs:
        for source in prog['sources']:
            run(CC, '-o',source+'.o', '-c', CFLAGS, source+'.c')

def link():
    for prog in programs:
        objects = [s+'.o' for s in prog['sources']]
        run(CC,LINKFLAGS,'-o', prog['name'], objects)

def clean():
    autoclean()


def install():
    import shutil

    # make sure everything is built first
    build()

    for target in install_targets:
        (name,subdir) = target
        subdir = os.path.join(prefix, subdir)
        if not os.path.exists(subdir):
            os.makedirs(subdir)

        dest=os.path.join(subdir, os.path.basename(name))
        print("install:",dest)
        shutil.copy(name, dest)

# send options so it won't crash on us
main(extra_options=optlist)

