#!/usr/bin/env python

from fabricate import *
import sys, os
import optparse


parser = optparse.OptionParser()
# make an options list, also send to fabricate
optlist=[optparse.Option('--prefix','-p',default=sys.exec_prefix)]
parser.add_options(optlist)

options,args = parser.parse_args()
prefix=os.path.expanduser( options.prefix )

CC='gcc'


CFLAGS=['-std=c99','-O2']
LINKFLAGS=[]

sources = ['Vector']

types=['f32',
       'f64',
       'i8',
       'u8',
       'i16',
       'u16',
       'i32',
       'u32',
       'i64',
       'u64',
       'char',
       'uchar',
       'sz']

def testname(type):
    return 'test-%svector' % type

# look for test programs to build
programs=[]
for type in types:
    name = testname(type)
    if os.path.exists(name+'.c'):
        programs += [{'name':name,'sources':sources+[name]}]

def build():
    compile()
    link()

def compile():
    for prog in programs:
        for source in prog['sources']:
            run(CC, '-c', CFLAGS, source+'.c')

def link():
    for prog in programs:
        objects = [s+'.o' for s in prog['sources']]
        run(CC,LINKFLAGS,'-o', prog['name'], objects)

def clean():
    autoclean()


def install():
    import shutil

    # make sure everything is built first
    build()

    for target in install_targets:
        (name,subdir) = target
        subdir = os.path.join(prefix, subdir)
        if not os.path.exists(subdir):
            os.makedirs(subdir)

        dest=os.path.join(subdir, os.path.basename(name))
        print("install:",dest)
        shutil.copy(name, dest)

# send options so it won't crash on us
main(extra_options=optlist)

