#!/usr/bin/env python
'''
    ./configure type1 type2 ...

Description

    Generate vector.h and vector.c for the input type list. See
    builtins, as well as a test file for each type. the types
    are listed in a yaml config file.

        ./configure conf.yaml

    for an example config see example-conf.yaml

    build test programs

        ./build-tests

    run test program, e.g. for doubles

        ./test-dvector
'''

import sys
import optparse
import vectypes

parser = optparse.OptionParser(__doc__)

def main():
    options, args = parser.parse_args(sys.argv[1:])
    if len(args) < 1:
        parser.print_help()
        sys.exit(1)

    conf_name=args[0]
    conf=vectypes.read_config(conf_name)
    g = vectypes.Generator(conf)
    g.write()

    #vectypes.generate_h(types)
    #vectypes.generate_c(types)
    #vectypes.generate_tests(types)

main()
