#!/bin/bash

backupdir=/Users/esheldon/oh/backups

if [ ! -d $backupdir ]
then
    echo "Could not find backups directory $backupdir"
    exit
fi

cd $backupdir
nbackup=30

# keep only nbackup copies. 
rm -rfv backup.$nbackup
for ((i = nbackup-1; i > 0; i--)); do
#for i in `seq -w 1 $nbackup`; do 

    ii=$[i+1]
    iistr=`printf "%02i" $ii`
    istr=`printf "%02i" $i`


    if [[ -d backup.$istr ]]; then
        mv -v backup.$istr backup.$iistr
    fi
done

/usr/bin/rsync -av --delete \
    --exclude "/Music" \
    --exclude "/News" \
    --exclude "/Movies" \
    --exclude "/BitTorrent" \
    --exclude "/.Trash" \
    --exclude "/Library/Caches" \
    --exclude "/src" \
    --exclude "/tmp" \
    --link-dest=../backup.02  ~/ backup.01/

