#!/bin/bash
#
# Backup home area to bias with machine specific exclude list in 
# ~/.doftiles/machine
#

if [ $# -lt 1 ]; then
    echo "usage: `basename $0` machine [bandwidth limit kbyte/s]"
    exit 45
fi

bwlimit=1000
if [ $# -gt 1 ]; then
	bwlimit=$2
fi

machine=$1
host=bias.cosmo.fas.nyu.edu

dt=`date "+%Y-%m-%dT%H:%M:%S"`
backup_name=backup-$dt
remote_backupdir=/mount/bias1/esheldon/backups/$machine


exclude_list=~/.dotfiles/backup_excludes/$machine

rsync -azxP --bwlimit=$bwlimit --delete --exclude-from=$exclude_list --link-dest=$remote_backupdir/current ~/ $host:$remote_backupdir/$backup_name/

ssh $host "cd $remote_backupdir && rm -f current && ln -s $backup_name current" 



echo Done
date
