#!/bin/bash

remote_backupdir=/global/bias1/esheldon/backups/fangorn/backup.01/
host=bias.cosmo.fas.nyu.edu

ssh $host "bash shell_scripts/backup_to_bias_prepare fangorn"

/usr/bin/rsync -av --delete \
    --exclude "/Music" \
    --exclude "/BitTorrent" \
    --exclude "/Pictures" \
    --exclude "/Library" \
    --exclude "/Documents" \
    --exclude "/svn" \
    --exclude "/talks_posters" \
    --exclude "/plots" \
    --exclude "/west_coast_trip2003_copy" \
    --exclude "/src" \
    --exclude "/tmp" \
    --exclude "/papers" \
    --exclude "/Movies" \
    --exclude "/rccny2" \
    --exclude "/shapelet_outputs" \
    --exclude "/.mozilla" \
    --exclude "/News" \
    --exclude "/.Trash" \
    --link-dest=../backup.02  ~/ $host:$remote_backupdir

