#!/bin/bash
# usage: bkuprohan [options]
#
# perform incremental backups using rsync
# 
# options is any string of the single letter options sent to rsync.
# e.g. 
#	bkuprohan P
# adds the -P option
#
# use this for a dry run
#    bkuprohan n
#
#  Note the options
#   -avx are already used, as well as longer
# ones --delete --exclude-from --link-dest

options=""
if [ $# -gt 0 ]; then
	options=$1
	options="-$options"
fi


backupdir=/media/havens/backups-rohan
cd $backupdir

if [ "$?" != "0" ]; then
	echo Could not cd to backup directory $backupdir
	exit 45
fi

dt=`date "+%Y-%m-%dT%H:%M:%S"`
backup_name=backup-rohan-$dt


exclude_list=~/.dotfiles/backup_excludes/rohan

command="
rsync
	-avx
	$options
	--delete
	--exclude-from=$exclude_list
	--link-dest=../current
	${HOME}/
	./$backup_name/
"

echo "executing rsync command:"
echo "$command"
$command

if [ -e current ]; then
	rm current
fi
ln -s $backup_name current
cd


echo Done
date
