#!/bin/bash

if [[ $# -lt 1 ]]; then
    echo "usage: colstats col1 col2 ..."
    echo "  send data on stdin"
    exit 1
fi

front=""
begin=""
cmd=""
prnt="print "
i=1
for col; do 
    begin="$begin
    mins[$col]=9999e50;
    maxes[$col]=-9999e50;
    "
    front="$front
    sum[$col] += \$$col;
    sum2[$col] += \$$col*\$$col;
    if (\$$col > maxes[$col]) maxes[$col]=\$$col;
    if (\$$col < mins[$col]) mins[$col]=\$$col;
    "

    cmd="$cmd
    mn[$col]=sum[$col]/NR;
    mn2[$col]=sum2[$col]/NR;
    std[$col]=sqrt( (mn2[$col] - mn[$col]*mn[$col]));
    err[$col]=sqrt( (mn2[$col] - mn[$col]*mn[$col])/NR);"

    if [[ $i -gt 1 ]]; then
        prnt="$prnt ,"
    fi
    prnt="$prnt \"min: \" mins[$col] \" max: \" maxes[$col] \" mean: \" mn[$col] \" +/- \" err[$col] \" std: \" std[$col]"

    i=$((i = i+1))
done

front="$front"

script="BEGIN {
    $begin
} {
    $front
} END {
    $cmd
    $prnt
}"

#echo "$script"

awk "$script" < /dev/stdin
