#!/bin/bash

function usage() {
    echo "Usage: curl-list url"
    echo "List the files in the url"
    echo "  If you need a username/password, put them in ~/.netrc"
}

full="n"
while getopts "f" Option; do
    case $Option in
        f) full="y" 
            ;;
        [?]) usage
             exit
            ;;  
    esac
done
shift $(($OPTIND - 1))


if [[ $# -lt 1 ]]; then
    usage
    exit 45
fi

url="$1"
url_list=$(curl -s -k --netrc-optional "$url"  | grep -v "Parent Directory" | grep -v "\?" | grep -i href | awk -F 'href="' '{print $2}' | awk -F '"' '{print $1}')


for turl in $url_list; do
    furl=$url/$turl
    echo $furl
    if [[ $full == "y" ]]; then
        curl -s -k --netrc-optional -I "$url/$turl"
    else
        echo $furl
    fi
done
