#!/bin/bash

function usage {
    echo "
    usage: incsub [-h -n maxjobs] file_list

        -n to specify the max number of allowed jobs in any queue. 
              default is 50.
        -h for this help message

    Incrementally submit wq jobs from the input file list, maintaining at most
    the specified number of jobs in the queues.  Jobs are submitted using
    nohup.  Wait 30 seconds between job checks

    If filename.out exists or filename with the extension removed and replaced
    by .out exists, the job will not be submitted.  Remove those files to
    get jobs to run.

    Outputs from wq are sent to file.wqlog
"
}

function count_jobs {
    name=$1

    # since we don't want the header, we demand the user field
    # equals the user instead of using -u to the qstat
    awk_name="{if (\$2 == \"$name\") print \$0}"
    njob=$(wq ls | awk "$awk_name" | wc -l)
    echo "$njob"
}

name=`whoami`

# number of jobs running at once
maxjobs=50
while getopts "hn:" Option; do
    case $Option in
        n) maxjobs=$OPTARG ;;
        h) usage
           exit 45 ;;
        [?]) usage
             exit 45 ;;
    esac
done
shift $(($OPTIND - 1))

if [ $# -lt 1 ]; then
    usage
    exit 45
fi

echo "submitting jobs for user: $name"
echo "number in list: $#"
echo "will limit to maxjobs:    $maxjobs"

for file; do
    outf1="$file.out"
    outf2="${file%.*}.out"
    logf="${file%.*}.wqlog"

    if [[ ! -e $outf1 && ! -e $outf2 ]]; then

        njob=$(count_jobs $name)
        while [[ $njob -ge $maxjobs ]]; do
            sleep 30
            njob=$(count_jobs $name $queue)
        done

        dt=`date +"%T"`
        echo "Found $njob jobs, submitting $file ($dt) "
        nohup wq sub "$file" &> "$logf" &
        sleep 1

    fi
done
