#!/bin/bash


function usage() {
    echo "Usage: mcurl [-d -u user:password -v verbosity -s] url"
    echo ""
    echo "Download all the files in a directory to the cwd"
    echo ""
    echo "options:"
    echo "  -d: dry run"
    echo "  -u: send the username and optionally password as user or user:pass"
    echo "  -v: set verbosity level, [0,2], default is 2, the most verbose"
    echo "  -s: set verbosity level to 0"
}
verbosity="2"


dryrun="n"
userpass=""
options="-k"
while getopts "du:sv:" Option; do
    case $Option in
        d) dryrun="y" 
            ;;
        u) userpass=$OPTARG
            ;;
        v) verbosity=$OPTARG
            ;;
        s) verbosity="0"
            ;;
        [?]) usage
             exit
            ;;  
    esac
done
shift $(($OPTIND - 1))

if [[ $# -lt 1 ]]; then
    usage
    exit 45
fi

if [[ $userpass != "" ]]; then
    flist_options="$options -u $userpass -s"
    main_options="$options -u $userpass"
fi
if [[ $verbosity != "2" ]]; then
    main_options="$options -s"
fi

url="$1"
flist=$(curl $flist_options "$url"  | grep -v "Parent Directory" | grep -v "\?" | grep -i href | awk -F 'href="' '{print $2}' | awk -F '"' '{print $1}')

urlprint=$url
if [[ $(echo $url | awk '{print substr($0,length,1)}') == "/" ]]; then
    urlprint=$(echo $url | awk '{print substr($0,0,length-1)}')
fi

for f in $flist; do
    lastchar=$(echo $f | awk '{print substr($0,length,1)}')

    if [[ $lastchar != "/" ]]; then
        if [[ $verbosity == "2" && $dryrun != "y" ]]; then
            echo
        fi
        if [[ $verbosity == "1" || $verbosity == "2" ]]; then
            echo "$urlprint/$f"
        fi
        if [[ $dryrun == "n" ]]; then
            curl $main_options -O "$url/$f"
        fi
    fi

done
