#!/bin/bash
#
# pvrm dir1 dir2 ... 
#
# remove the directories recursively, with progress bar using pv
#

# exit when any command fails
set -e

if [[ $# -lt 1 ]]; then
    echo "pvrm dir1 dir2 ..."
    exit 1
fi

for dir; do

    if [[ ! -e "$dir" ]]; then
        echo "directory does not exist: $dir"
        exit 1
    fi


    # -l means count lines.  -s then give number of lines
    # -p means show a progress bar
    # -e means show eta
    # -t means show timer, how long pv has been running
    # -b show total line counter (means bytes if -l were not sent)
    # -s means the following argument is the expected number of lines
    #    (s for size)

    echo -n "counting files in $dir: "
    nfiles=$(find "$dir" | wc -l)
    echo "$nfiles"

    echo "removing directory"
    rm -rv "$dir" | pv -w 80 -lpetbs "$nfiles" > /dev/null

done
