#!/bin/bash

if [[ $# -lt 1 ]]; then
    echo "random-password num"
    exit 1
fi

num=$1

#</dev/urandom tr -dc '12345!@#$%qwertQWERTasdfgASDFGzxcvbZXCVB' | head -c${num}; echo ""
#</dev/urandom tr -dc '123456789!@#$%_abcdefghijklmnopqrstuvwxyz' | head -c${num}; echo ""
</dev/urandom tr -dc '1-9a-zA-Z!@#$%_' | head -c${num}; echo ""
