#!/bin/bash
#
# rslocal src dest
#
# wrapper for rsync optimized for local transfers.
#
# the output directory is created if it does not exist.
#

# exit when any command fails
set -e

if [[ $# -lt 2 ]]; then
    echo "rslocal src dest"
    exit 1
fi

src=$1
dest=$2

if [[ ! -e $src ]]; then
    echo "input directory does not exist: $src"
    exit 1
fi

if [[ ! -e $dest ]]; then
    echo "making output directory: $dest"
    mkdir -p "$dest"
fi

# --no-inc-recursive forces the entire to be found so we know exactly how far
#   along the transfer is
# --progress print progress information
# --partial-dir=.rsync-partial   put partial files there, relative to dest
# -a archive mode
# -v verbose
# -h human readable for --progress
# -H preserve hard links
# not uses: -W transfer whole files (might be redundant for local copies)

rsync                            \
    --no-inc-recursive           \
    --progress                   \
    --partial-dir=.rsync-partial \
    -ahH                         \
    "$src/"                      \
    "$dest/"
