#!/bin/bash
#
# tarcp indir outdir
#
# copy the input directory into the output directory.
# the output directory is created if it does not exist.
#

if [[ $# -lt 2 ]]; then
    echo "tarcp indir outdir"
    exit 1
fi

indir=$1
outdir=$2
if [[ ! -e $outdir ]]; then
    echo "making output directory: $outdir"
    mkdir -p "$outdir"
fi

outdir_abs=$(readlink -m $outdir)

cd "$indir"
tar cf - . | (cd "$outdir_abs" && tar --keep-newer-files -x -v -f -)
