#!/bin/bash

function usage {
    echo "
    usage: wqtail [-h -n nfiles -c columns -E limit -l] dir

        Tail recently changed .wqlog files.  By default follow the latest using
        less +F.  If more are requested then multitail is used.

    options:
        -n Number of files to watch, default 1
        -c Number of columns to use in display if n > 1
        -E Limit to lines matching the input regular expression
        -l Use less on one file
        -h for this help message
"
}


nfiles=1
ncols=1
limit="None"
use_less="No"
while getopts "hn:c:E:l" Option; do
    case $Option in
        n) nfiles=$OPTARG ;;
        c) ncols=$OPTARG ;;
        E) limit=$OPTARG ;;
        l) use_less="Yes";;
        h) usage
           exit 1 ;;
        [?]) usage
             exit 1 ;;
    esac
done
shift $(($OPTIND - 1))


if [ $# -lt 1 ]; then
    usage
    exit 1
fi

dir="$1"

if [[ $nfiles == "1" && $use_less == "Yes" ]]; then
    cmd="less +F"
else
    cmd="multitail"
    if [[ $ncols != 1 ]]; then
        cmd="$cmd -s $ncols"
    fi
    if [[ $limit != "None" ]]; then
        #cmd="$cmd -E \"$limit\""
        cmd="$cmd -E $limit"
    fi
fi
cmd="$cmd $(ls -t $dir/*.wqlog | head -$nfiles)"

$cmd
