--- 
:confirm_no_attachments: true
:wrap_width: 80
:confirm_top_posting: true
:editor: vim + -f -c 'setlocal spell spelllang=en_us' -c 'set filetype=mail'
:ask_for_to: true
:accounts: 
  :default: 
    :signature: /home/esheldon/.signature
    :sendmail: msmtp --account=gmail -t
    :alternates: 
    - esheldon@bnl.gov
    - esheldon@kicp.uchicago.edu
    - esheldon@cfcp.uchicago.edu
    - esheldon@umich.edu
    - esheldon@sdss4.physics.lsa.umich.edu
    :name: Erin Sheldon
    :email: erin.sheldon@gmail.com
:jump_to_open_message: true
:sent_source: sup://sent
:ask_for_cc: true
:discard_snippets_from_encrypted_messages: false
:ask_for_bcc: false
:thread_by_subject: false
:default_attachment_save_dir: ~/downloads
:ask_for_subject: true
:edit_signature: false
:poll_interval: 300
