--- 
- !masanjin.net,2006-10-01/Redwood/Maildir 
  uri: maildir:~/gmail-archive/
  cur_offset: 
  usual: true
  archived: false
  id: 1
  labels: 
  - gmail-archive
  mtimes: 
    cur: 1969-12-31 19:00:00 -05:00
    new: 1969-12-31 19:00:00 -05:00
- !masanjin.net,2006-10-01/Redwood/Maildir 
  uri: maildir:~/gmail
  cur_offset: 
  usual: true
  archived: false
  id: 2
  labels: 
  - gmail
  mtimes: 
    cur: 1969-12-31 19:00:00 -05:00
    new: 1969-12-31 19:00:00 -05:00
