--- 
- !masanjin.net,2006-10-01/Redwood/Maildir 
  uri: maildir:~/gmail/
  cur_offset: 13199946210002896
  usual: true
  archived: false
  id: 1
  labels: 
  - gmail
  mtimes: 
    cur: 2011-10-30 12:53:58 -04:00
    new: 2011-10-30 13:10:21 -04:00
