#!/usr/bin/perl -w
# Convert a comma separated value file (csv) to a space separated
# value file

if (@ARGV < 1) {
    print "-Syntax: csv2dat cvsFile\n";
    exit;
}

while (<>) {
    $_ =~ s/,/ /g;
    print;
}
