#
#
#	PACKAGE:	SpatialIndex
#

# --- Targets ----------------------------------------------------------------

default: all

all clean :
	@ cd src/htm; ${MAKE} $@
	@ cd src; ${MAKE} $@

test:
	@cd src; ${MAKE} $@

test-gcirc:
	@cd src; ${MAKE} $@
test-scat:
	@cd src; ${MAKE} $@
test-lcat:
	@cd src; ${MAKE} $@

